root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md
  # glossary: GLOSSARY.md
  introduction: introduction.md
branch: main
title: Emmet.Finance Public Documentation
description: Emmet.Finance Public Documentation